AWSTemplateFormatVersion: '2010-09-09'
Description: Application Load Balancer

Parameters:
  VPCId:
    Type: AWS::EC2::VPC::Id
  SubnetId:
    Type: List<AWS::EC2::Subnet::Id>
  TargetInstanceId:
    Type: String

Resources:
  LoadBalancerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: MyTargetGroup
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPCId
      TargetType: instance
      Targets:
        - Id: !Ref TargetInstanceId

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MyALB
      Subnets: !Ref SubnetId
      SecurityGroups:
        - !Ref LoadBalancerSG
      Scheme: internet-facing
      Type: application

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

Outputs:
  LoadBalancerDNS:
    Description: DNS of ALB
    Value: !GetAtt ApplicationLoadBalancer.DNSName

