AWSTemplateFormatVersion: '2010-09-09'
Description: Basic EC2 Instance

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0


  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref EC2SecurityGroup
      ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2 (us-east-1)
      UserData: !Base64 |
                #!/bin/bash
                # Update the instance and install Nginx
                yum update -y
                amazon-linux-extras enable nginx1
                yum install -y nginx
                # Start and enable Nginx service
                systemctl start nginx
                systemctl enable nginx
                                                                                                
      Tags:               
        - Key: Name  
          Value: MyCloudFormationEC2

Outputs:
  InstanceId:
    Description: Instance ID
    Value: !Ref EC2Instance
  PublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp

